
services:
  app:
    build: .
    container_name: vuejs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=3000
    command: npm run dev -- --host 0.0.0.0 --port 3000 